version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: exam_bud
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file: ./backend/.env
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - ./backend/uploads:/usr/src/app/uploads

  test:
    build: ./backend
    environment:
      DATABASE_URL: "postgresql://prisma:prisma@db:5432/exam_bud_test"
      NODE_ENV: test
    depends_on:
      - db
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    entrypoint: []
    command: sh -c "
      echo 'waiting for database...';
      until nc -z db 5432; do sleep 1; done;
      echo 'creating test database...';
      PGPASSWORD=prisma psql -h db -U prisma -d exam_bud -c 'CREATE DATABASE exam_bud_test;' 2>/dev/null || echo 'Test database already exists';
      echo 'regenerating prisma client';
      npx prisma generate;
      echo 'setting up database schema...';
      npx prisma db push;
      echo 'running tests...';
      npm test"
    profiles:
      - test

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3001:3001"

volumes:
  db-data:
